# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 22:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_auto_20160517_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighestPointsOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('winners', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_type',
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Highest Wins'), (1, 'IRV'), (2, 'Fill-in'), (3, 'Highest Points')], default=0),
        ),
        migrations.AddField(
            model_name='highestpointsoptions',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voting.Question'),
        ),
    ]
